<?php

namespace ContainerPxokFAr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Api_Validator_ShipmentAlreadyShippedService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.api.validator.shipment_already_shipped' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Validator\Constraints\ShipmentAlreadyShippedValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Validator/Constraints/ShipmentAlreadyShippedValidator.php';

        return $container->privates['sylius.api.validator.shipment_already_shipped'] = new \Sylius\Bundle\ApiBundle\Validator\Constraints\ShipmentAlreadyShippedValidator(($container->services['sylius.repository.shipment'] ?? $container->load('getSylius_Repository_ShipmentService')));
    }
}
