<?php

namespace ContainerPxokFAr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSylius_Api_Validator_ConfirmResetPasswordService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sylius.api.validator.confirm_reset_password' shared service.
     *
     * @return \Sylius\Bundle\ApiBundle\Validator\Constraints\ConfirmResetPasswordValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/validator/ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).'/vendor/sylius/sylius/src/Sylius/Bundle/ApiBundle/Validator/Constraints/ConfirmResetPasswordValidator.php';

        return $container->privates['sylius.api.validator.confirm_reset_password'] = new \Sylius\Bundle\ApiBundle\Validator\Constraints\ConfirmResetPasswordValidator();
    }
}
